### ISSUE TITLE
How to pass only a single chain?

### ISSUE THREAD

**Issue by jaydeepsb** [PDB-REDO/dssp#13]
Dear authors, I wish to get accessible surface area values. Suppose a structure has two chains A,B, then when I pass the file (pdb or cif), DSSP calculates the ASA for all the chains present in it together. However, I want to calculate ASA, lets say, chain A and B separately and then together A,B. I could not find any help in the documentation on how to do it? Is it possible?

**Comment by drlemmus** [comment]
The best (and probably only) way to achieve this is by running DSSP three times. Once on the whole model, and twice on a model containing only one of the two chains. Your specific calculation might also benefit from using PISA. That is specifically designed to do these sort of analyses.
