### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by spydr1** [PDB-REDO/dssp#16]
i'm using docker. 
i want to install in my container. 

"""
when i installed mrc , i encountered error

./configure
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++17 features with -std=c++17... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for boostlib >= 1.65.1 (106501)... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether the Boost::Program_Options library is available... yes
checking for main in -lboost_program_options... yes
checking how to run the C++ preprocessor... g++ -std=c++17 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking filesystem usability... no
checking filesystem presence... no
checking for filesystem... no
configure: error: The file <filesystem> is missing, perhaps you should install a more recent libstdc++ implementation.
"""

env 
"""
clang --version
clang version 10.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /clang_10/bin

gcc --version
gcc (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.

make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

"""

how can i solve it ? 
i need your help ! 

thanks !

**Comment by mhekkel** [comment]
Looks like your dockerfile is incorrect, loading the wrong stuff. Have a look at https://github.com/PDB-REDO/pdb-redo-builder for inspiration on how to solve this.
