### ISSUE TITLE
./configure: line 2068: syntax error near unexpected token `noext'

### ISSUE THREAD

**Issue by zengchuan-max** [PDB-REDO/dssp#18]
Dear 
   I encountered some problems during the installation.
   
  ~/software/dssp-trunk$ ./configure
   ./configure: line 2068: syntax error near unexpected token `noext'
   ./configure: line 2068: `AX_CXX_COMPILE_STDCXX_17(noext)'

  what should I do with it?

**Comment by mhekkel** [comment]
GNU autoconf is no longer used, this issue should be fixed now.
