### ISSUE TITLE
DSSP 4.0 can't be compiled

### ISSUE THREAD

**Issue by lokapal** [PDB-REDO/dssp#2]
Ubuntu Linux 16.04 LTS latest patches, BOOST 1.74.0, libcif++ and MRC are installed successfully. Configure finishes successfully, but make fails:
./configure
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++-9 accepts -g... yes
checking whether g++-9 supports C++17 features with -std=c++17... yes
checking whether C++ compiler accepts -fstandalone-debug... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for mrc... /usr/local/bin/mrc
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc-9
checking whether we are using the GNU C compiler... yes
checking whether gcc-9 accepts -g... yes
checking for gcc-9 option to accept ISO C89... none needed
checking for a sed that does not truncate output... /bin/sed
checking how to run the C preprocessor... gcc-9 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc-9 is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking how to run the C++ preprocessor... g++-9 -std=c++17 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking filesystem usability... yes
checking filesystem presence... yes
checking for filesystem... yes
checking for boostlib >= 1.65.1 (106501)... configure: We will use a staged boost library from /root/boost_1_74_0
yes
checking whether the Boost::IOStreams library is available... yes
checking for exit in -lboost_iostreams... yes
checking whether the Boost::Program_Options library is available... yes
checking for exit in -lboost_program_options... yes
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for pkg-config... /usr/bin/pkg-config
checking for CIFPP... yes
configure: creating ./config.status
config.status: creating GNUmakefile
config.status: creating src/config.hpp

root@host:~/dssp# make -j4
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
mkdir -p obj
rm -f version-info-*.txt
fatal: Not a git repository (or any of the parent directories): .git
GNUmakefile:115: recipe for target 'version-info-.txt' failed
make: *** [version-info-.txt] Error 128

gcc-9 (Ubuntu 9.3.0-10ubuntu2~16.04) 9.3.0
g++-9 (Ubuntu 9.3.0-10ubuntu2~16.04) 9.3.0

**Comment by lokapal** [comment]
git --version
git version 2.7.4

**Comment by mhekkel** [comment]
Yup, that was an error. Should be fixed in the latest commit.

Thanks for reporting
