### ISSUE TITLE
‘addFileResource’ is not a member of ‘cif’

### ISSUE THREAD

**Issue by poinco-gogo** [PDB-REDO/dssp#22]
Dear developers,
i have encountered following issues during compiling mkdssp.cpp:

src/mkdssp.cpp: In function 'int d_main(int, const char**)':
src/mkdssp.cpp:532:8: error: 'addFileResource' is not a member of 'cif'
  532 |   cif::addFileResource("components.cif", vm["compounds"].as<std::string>());
      |        ^~~~~~~~~~~~~~~
src/mkdssp.cpp:534:8: error: 'addFileResource' is not a member of 'cif'
  534 |   cif::addFileResource("components.cif", vm["components"].as<std::string>());
      |        ^~~~~~~~~~~~~~~
src/mkdssp.cpp:542:8: error: 'addFileResource' is not a member of 'cif'
  542 |   cif::addFileResource("mmcif_pdbx_v50.dic", vm["mmcif-dictionary"].as<std::string>());
      |        ^~~~~~~~~~~~~~~
make: *** [obj/mkdssp.o] Error 1

i have already installed libcifpp ver 1.0.0 and boost ver 1.76.0
the compilation is carried out with gnu compiler ver 9.3.0
what can i do with the problem??
thank you very much in advance

Koichi

**Comment by poinco-gogo** [comment]
i installed the latest version of libcif++ and the problem went away...
sorry to bother you!

Koichi

**Comment by mhekkel** [comment]
Thanks for the update. I was already scratching my head what might be 
wrong here....

-maarten

Op 15-7-2021 om 16:29 schreef Koichi TAMURA:
