### ISSUE TITLE
Tag 4.0.0 release

### ISSUE THREAD

**Issue by pacho2** [PDB-REDO/dssp#24]
Hello, 

I was trying to download the official tarball for dssp-4.0.0 but I couldn't find it. Before cloning the git repo, I thought that maybe tagging a 4.0.0 release here would also help others (like other downstreams trying to package updated dssp for their distributions)

Thanks a lot

**Comment by mhekkel** [comment]
https://github.com/PDB-REDO/dssp/releases/tag/v4.0.2

Hope that's what you were asking for?

**Comment by pacho2** [comment]
Yes, thanks

But no idea about why Releases are not listed in the right bar from:
https://github.com/PDB-REDO/dssp

As it's done with https://github.com/PDB-REDO/libcifpp (below "About" information)

**Comment by mhekkel** [comment]
Op 3-10-2021 om 20:24 schreef Pacho Ramos:
> Yes, thanks
> 
> But no idea about why Releases are not listed in the right bar from:
> https://github.com/PDB-REDO/dssp <https://github.com/PDB-REDO/dssp>

Appears to be a setting, just toggled the switch and now you can see the 
releases.

Thanks for pointing out, didn't know this.

regards, -maarten
