### ISSUE TITLE
GNUmakefile does not honor DESTDIR for some files

### ISSUE THREAD

**Issue by pacho2** [PDB-REDO/dssp#25]
When running make DESTDIR=... install , it still tries to install some files out of the wanted location

This patch solves it:
```
--- a/GNUmakefile.in.old	2021-08-31 12:04:11.657975463 +0200
+++ b/GNUmakefile.in	2021-08-31 12:05:01.753610209 +0200
@@ -48,7 +48,7 @@
 bindir				= @bindir@
 datarootdir			= @datarootdir@
 datadir				= @datadir@
-mandir				= @mandir@
+mandir				= $(DESTDIR)@mandir@
 
 GNUmakefile: config.status GNUmakefile.in
 	$(SHELL) ./config.status
```

Thanks

**Comment by mhekkel** [comment]
dssp no longer uses GNU autoconf/GNU makefiles, so this should no longer be an issue. Unless cmake does not work work as you expect it should, in that case please open a new issue.
