### ISSUE TITLE
Compilation on OSX fails due to boost dependency

### ISSUE THREAD

**Issue by piehld** [PDB-REDO/dssp#29]
Trying to build the program from source code seems to fail on OSX (10.15), due to an issue related to the boost dependency `licudata`. This issue has been reported by others in separate applications as well: [Ref. 1](https://github.com/Homebrew/homebrew-core/issues/67427), [Ref. 2](https://github.com/boostorg/boost_install/issues/47). 

Based on some of the comments from those issues, I was able to resolve the installation here by removing the following lines from the `CMakeLists.txt` file (148–150, primarily the `Boost_USE_STATIC_LIBS` setting):
```
if(NOT BUILD_SHARED_LIBS)
	set(Boost_USE_STATIC_LIBS ON)
endif()
```

However, this seems like a bit of a hack, so I'd like to report the issue here for your review as well.

**Comment by piehld** [comment]
To provide more information on the error that arises during build, here is what occurs:
```
~/dssp/build % cmake --build . --config Release 
[ 16%] Building CXX object CMakeFiles/mkdssp.dir/src/dssp.cpp.o
[ 33%] Building CXX object CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o
[ 50%] Linking CXX executable mkdssp
ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mkdssp] Error 1
make[1]: *** [CMakeFiles/mkdssp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mhekkel** [comment]
The trouble here is that the boost libraries do not contain the correct dependency list in their cmake config file. In theory, cmake config files should specify what is needed to correctly link a library. In the case of boost this means you need the library icudata but also the path to this library.

BTW, the lines you commented out were in fact a hack from my side. They are gone in the latest version.
