### ISSUE TITLE
error when running cmake --build . --config Release

### ISSUE THREAD

**Issue by Chengeng-Yang** [PDB-REDO/dssp#35]
Hi there,

I'm having difficulty in installing the dspp package -- I've installed boost 1.78 and libcif++ from source code and the issue I've having seems like to be related to the failure of linking zlib and bzip2 to dssp and boost. Please find the error message below:

CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `d_main(int, char const**)':
mkdssp.cpp:(.text+0x1aed): undefined reference to `boost::iostreams::zlib::default_strategy'
mkdssp.cpp:(.text+0x1af3): undefined reference to `boost::iostreams::zlib::deflated'
mkdssp.cpp:(.text+0x1af9): undefined reference to `boost::iostreams::zlib::default_compression'
CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `boost::iostreams::basic_gzip_compressor<std::allocator<char> >::basic_gzip_compressor(boost::iostreams::gzip_params const&, long)':
mkdssp.cpp:(.text._ZN5boost9iostreams21basic_gzip_compressorISaIcEEC2ERKNS0_11gzip_paramsEl[_ZN5boost9iostreams21basic_gzip_compressorISaIcEEC5ERKNS0_11gzip_paramsEl]+0x1a7): undefined reference to `boost::iostreams::zlib::best_compression'
mkdssp.cpp:(.text._ZN5boost9iostreams21basic_gzip_compressorISaIcEEC2ERKNS0_11gzip_paramsEl[_ZN5boost9iostreams21basic_gzip_compressorISaIcEEC5ERKNS0_11gzip_paramsEl]+0x1c6): undefined reference to `boost::iostreams::zlib::best_speed'
CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `boost::iostreams::detail::zlib_compressor_impl<std::allocator<char> >::zlib_compressor_impl(boost::iostreams::zlib_params const&)':
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEEC2ERKNS0_11zlib_paramsE[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEEC5ERKNS0_11zlib_paramsE]+0x19): undefined reference to `boost::iostreams::detail::zlib_base::zlib_base()'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEEC2ERKNS0_11zlib_paramsE[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEEC5ERKNS0_11zlib_paramsE]+0x5e): undefined reference to `boost::iostreams::detail::zlib_base::~zlib_base()'
CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `boost::iostreams::detail::zlib_compressor_impl<std::allocator<char> >::~zlib_compressor_impl()':
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEED2Ev[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEED5Ev]+0x1e): undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEED2Ev[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEED5Ev]+0x36): undefined reference to `boost::iostreams::detail::zlib_base::~zlib_base()'
CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `void boost::iostreams::detail::zlib_base::init<std::allocator<char> >(boost::iostreams::zlib_params const&, bool, boost::iostreams::detail::zlib_allocator<std::allocator<char>, boost::iostreams::detail::zlib_allocator_traits<std::allocator<char> >::type>&)':
mkdssp.cpp:(.text._ZN5boost9iostreams6detail9zlib_base4initISaIcEEEvRKNS0_11zlib_paramsEbRNS1_14zlib_allocatorIT_NS1_21zlib_allocator_traitsIS9_E4typeEEE[_ZN5boost9iostreams6detail9zlib_base4initISaIcEEEvRKNS0_11zlib_paramsEbRNS1_14zlib_allocatorIT_NS1_21zlib_allocator_traitsIS9_E4typeEEE]+0x5f): undefined reference to `boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)'
CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `boost::iostreams::detail::zlib_compressor_impl<std::allocator<char> >::filter(char const*&, char const*, char*&, char*, bool)':
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x3d): undefined reference to `boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x4d): undefined reference to `boost::iostreams::zlib::finish'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x55): undefined reference to `boost::iostreams::zlib::no_flush'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x5f): undefined reference to `boost::iostreams::detail::zlib_base::xdeflate(int)'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x7b): undefined reference to `boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x85): undefined reference to `boost::iostreams::zlib_error::check(int)'
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x8b): undefined reference to `boost::iostreams::zlib::stream_end'
CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o: In function `boost::iostreams::detail::zlib_compressor_impl<std::allocator<char> >::close()':
mkdssp.cpp:(.text._ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE5closeEv[_ZN5boost9iostreams6detail20zlib_compressor_implISaIcEE5closeEv]+0x1e): undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `cif::File::save(std::filesystem::__cxx11::path const&)':
Cif++.cpp:(.text+0x124e3): undefined reference to `boost::iostreams::zlib::default_strategy'
Cif++.cpp:(.text+0x124ec): undefined reference to `boost::iostreams::zlib::deflated'
Cif++.cpp:(.text+0x124f5): undefined reference to `boost::iostreams::zlib::default_compression'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::gzip_error::gzip_error(int)':
Cif++.cpp:(.text._ZN5boost9iostreams10gzip_errorC2Ei[_ZN5boost9iostreams10gzip_errorC5Ei]+0x69): undefined reference to `boost::iostreams::zlib::okay'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::detail::gzip_header::gzip_header()':
Cif++.cpp:(.text._ZN5boost9iostreams6detail11gzip_headerC2Ev[_ZN5boost9iostreams6detail11gzip_headerC5Ev]+0x31): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::detail::gzip_footer::gzip_footer()':
Cif++.cpp:(.text._ZN5boost9iostreams6detail11gzip_footerC2Ev[_ZN5boost9iostreams6detail11gzip_footerC5Ev]+0x14): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::basic_gzip_decompressor<std::allocator<char> >::make_params(int)':
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE11make_paramsEi[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE11make_paramsEi]+0x68): undefined reference to `boost::iostreams::zlib::default_strategy'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE11make_paramsEi[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE11make_paramsEi]+0x71): undefined reference to `boost::iostreams::zlib::deflated'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE11make_paramsEi[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE11make_paramsEi]+0x7a): undefined reference to `boost::iostreams::zlib::default_compression'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::detail::zlib_decompressor_impl<std::allocator<char> >::zlib_decompressor_impl(boost::iostreams::zlib_params const&)':
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEEC2ERKNS0_11zlib_paramsE[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEEC5ERKNS0_11zlib_paramsE]+0x19): undefined reference to `boost::iostreams::detail::zlib_base::zlib_base()'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEEC2ERKNS0_11zlib_paramsE[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEEC5ERKNS0_11zlib_paramsE]+0x66): undefined reference to `boost::iostreams::detail::zlib_base::~zlib_base()'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::detail::zlib_decompressor_impl<std::allocator<char> >::~zlib_decompressor_impl()':
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEED2Ev[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEED5Ev]+0x1e): undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEED2Ev[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEED5Ev]+0x36): undefined reference to `boost::iostreams::detail::zlib_base::~zlib_base()'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `long boost::iostreams::basic_gzip_decompressor<std::allocator<char> >::write<boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> > >(boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >&, char const*, long)':
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x67): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x77): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0xba): undefined reference to `boost::iostreams::detail::gzip_header::process(char)'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE5writeINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_PKcl]+0x20b): undefined reference to `boost::iostreams::detail::gzip_footer::process(char)'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::detail::zlib_decompressor_impl<std::allocator<char> >::filter(char const*&, char const*, char*&, char*, bool)':
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x3d): undefined reference to `boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x48): undefined reference to `boost::iostreams::zlib::sync_flush'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x54): undefined reference to `boost::iostreams::detail::zlib_base::xinflate(int)'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x70): undefined reference to `boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x7a): undefined reference to `boost::iostreams::zlib_error::check(int)'
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE6filterERPKcS6_RPcS8_b]+0x81): undefined reference to `boost::iostreams::zlib::stream_end'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `boost::iostreams::detail::zlib_decompressor_impl<std::allocator<char> >::close()':
Cif++.cpp:(.text._ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE5closeEv[_ZN5boost9iostreams6detail22zlib_decompressor_implISaIcEE5closeEv]+0x26): undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'
/home/chengeng/.local/lib/libcifpp.a(Cif++.cpp.o): In function `long boost::iostreams::basic_gzip_decompressor<std::allocator<char> >::read<boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> > >(boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >&, char*, long)':
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0xc4): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0xd7): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x160): undefined reference to `boost::iostreams::detail::gzip_header::process(char)'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x2dd): undefined reference to `boost::iostreams::detail::gzip_footer::process(char)'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x3d1): undefined reference to `boost::iostreams::detail::gzip_header::reset()'
Cif++.cpp:(.text._ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl[_ZN5boost9iostreams23basic_gzip_decompressorISaIcEE4readINS0_6detail16linked_streambufIcSt11char_traitsIcEEEEElRT_Pcl]+0x3e4): undefined reference to `boost::iostreams::detail::gzip_footer::reset()'
/home/chengeng/.local/lib/libcifpp.a(Structure.cpp.o): In function `mmcif::FileImpl::save(std::filesystem::__cxx11::path const&)':
Structure.cpp:(.text+0xeec): undefined reference to `boost::iostreams::zlib::default_strategy'
Structure.cpp:(.text+0xef5): undefined reference to `boost::iostreams::zlib::deflated'
Structure.cpp:(.text+0xefe): undefined reference to `boost::iostreams::zlib::default_compression'
collect2: error: ld returned 1 exit status
CMakeFiles/mkdssp.dir/build.make:117: recipe for target 'mkdssp' failed
make[2]: *** [mkdssp] Error 1
CMakeFiles/Makefile2:814: recipe for target 'CMakeFiles/mkdssp.dir/all' failed
make[1]: *** [CMakeFiles/mkdssp.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

--------------------------------------------------------------------------------------------------------------------------------------

I've tried multiple approaches but had zero success.

1. install zlib and bzip2 using sudo apt-get install libbz2-dev zlib1g-dev, compile boost then compile dssp -- doesn't work

2. compile boost including flags such as -sZLIB_INCLUDE=xyz in order to specify the path of zlib/bzip2 for boost then compile dssp -- doesn't work

3. have zlib and bzip2 package files ready and/or specify their path (e.g. using zlib : 1.2.10 : <source>/home/chengeng/Downloads/zlib-1.2.10 ;) in the user-config.jam file so that they can be built by boost before compiling dssp -- doesn't work

4. install zlib and bzip2 packages from source code in the default path and/or specify their path (e.g. using zlib : 1.2.10 : <include>/usr/local/include <search>/usr/local/lib ;) in the user-config.jam file so that they can be built by boost before compiling dssp -- doesn't work

In this case, could you help me with installation? My OS is Ubuntu 18.04 and I'm using gcc 10. I would really appreciate it if you could tell me the version of zlib, bzip2 and boost you are using when you compile this dssp package. Many thanks!

**Comment by mhekkel** [comment]
The error you see, about not finding the zlib symbols, means you are linking to static boost libraries. That means, you installed boost yourself and built only static libs. Could that be the case?
I may have to edit the CMakeLists.txt file for libcifpp again to include zlib in case that is needed. That may take some time. If you need a quick solution you can use the cmake macro BOOST_ROOT. Install the system libraries (apt-get install libboost-all-dev) and configure libcifpp with `cmake .. -DBOOST_ROOT=/usr/ `. Didn't test it, but might work. Mind you, you need to rebuild libcifpp and dssp this way using the same boost root location for each.
Oh, and build the shared libraries instead of the static ones. Otherwise you still need to link to zlib.

**Comment by mhekkel** [comment]
Hmmm, looking at the CMakeLists.txt file for libcifpp, I see that zlib should be included if you have static boost libraries. You might want to build libcifpp with -DBoost_USE_STATIC_LIBS=ON. I think that will solve the problem.

**Comment by Chengeng-Yang** [comment]
> Hmmm, looking at the CMakeLists.txt file for libcifpp, I see that zlib should be included if you have static boost libraries. You might want to build libcifpp with -DBoost_USE_STATIC_LIBS=ON. I think that will solve the problem.

Thanks for your replies -- The system libraries of boost (apt-get install libboost-all-dev) may not be suitable in this case because the most recent version supported is 1.65 (but dssp requires 1.70).

So I just tried building libcifpp like you said, using cmake .. -DBoost_USE_STATIC_LIBS=ON, before building dssp. But I still failed to run cmake --build . --config Release and there's a new warning message about runtime library (bold and italic) when I ran the previous command, cmake:

$ cmake 
Consolidate compiler generated dependencies of target mkdssp
[ 16%] Building CXX object CMakeFiles/mkdssp.dir/src/dssp.cpp.o
[ 33%] Building CXX object CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libz.so', needed by 'mkdssp'.  Stop.
CMakeFiles/Makefile2:814: recipe for target 'CMakeFiles/mkdssp.dir/all' failed
make[1]: *** [CMakeFiles/mkdssp.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
(base) chengeng@Chengeng-Ubuntu:~/Downloads/dssp-trunk/build$ cmake ..
CMake Warning at CMakeLists.txt:102 (find_package):
  By not providing "FindMrc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Mrc", but
  CMake did not find one.

  Could not find a package configuration file provided by "Mrc" with any of
  the following names:

    MrcConfig.cmake
    mrc-config.cmake

  Add the installation prefix of "Mrc" to CMAKE_PREFIX_PATH or set "Mrc_DIR"
  to a directory containing one of the above files.  If "Mrc" provides a
  separate development package or SDK, be sure it has been installed.


CMake Warning at CMakeLists.txt:107 (message):
  Not using resources since mrc was not found


-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.70.0") found components: system iostreams regex 
-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: date_time program_options 
-- Configuring done

**_CMake Warning at CMakeLists.txt:126 (add_executable):
  Cannot generate a safe runtime search path for target mkdssp because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.


CMake Warning at CMakeLists.txt:156 (add_executable):
  Cannot generate a safe runtime search path for target unit-test because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly._**


-- Generating done
-- Build files have been written to: /home/chengeng/Downloads/dssp-trunk/build

---------------------------------------------------------------------------------------------------------------
$ cmake --build . --config Release
Consolidate compiler generated dependencies of target mkdssp
[ 16%] Building CXX object CMakeFiles/mkdssp.dir/src/dssp.cpp.o
[ 33%] Building CXX object CMakeFiles/mkdssp.dir/src/mkdssp.cpp.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libz.so', needed by 'mkdssp'.  Stop.
CMakeFiles/Makefile2:814: recipe for target 'CMakeFiles/mkdssp.dir/all' failed
make[1]: *** [CMakeFiles/mkdssp.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

---------------------------------------------------------------------------------
in this case, do you have suggestions on defining the path for runtime libraries? I also tried compiling libcifpp using cmake .. -DBoost_USE_STATIC_LIBS=ON -DBOOST_ROOT=/usr/ but it didn't work either.

**Comment by Chengeng-Yang** [comment]
Hi there,

I actually switched over to a virtual machine under ubuntu 20.04 system, where I was available to install libboost 1.74 from sudo apt-get install and successfully compile this dssp package -- except for the mrc not found issue, but that's probably okay because mrc is optional.

But I'm having difficulty when running this program, both with or without gromacs.

When running with gromacs, it just reads the first frame and gets stuck from there, no matter how large my input file is:
Command line:
  gmx do_dssp -s md5_1000ns.tpr -f npt5.gro -sc test-new-dssp.xvg -o test-new-dssp.xpm -n 1-50.ndx

Reading file md5_1000ns.tpr, VERSION 2018 (single precision)
Reading file md5_1000ns.tpr, VERSION 2018 (single precision)
Not all residues were recognized (678 from 106546), the result may be inaccurate!
Group     0 (         System) has 326182 elements
Group     1 (        Protein) has  8714 elements
Group     2 (      Protein-H) has  4271 elements
Group     3 (        C-alpha) has   698 elements
Group     4 (       Backbone) has  2094 elements
Group     5 (      MainChain) has  2791 elements
Group     6 (   MainChain+Cb) has  3281 elements
Group     7 (    MainChain+H) has  3402 elements
Group     8 (      SideChain) has  5312 elements
Group     9 (    SideChain-H) has  1480 elements
Group    10 (    Prot-Masses) has  8714 elements
Group    11 (    non-Protein) has 317468 elements
Group    12 (          Water) has 317430 elements
Group    13 (            SOL) has 317430 elements
Group    14 (      non-Water) has  8752 elements
Group    15 (            Ion) has    38 elements
Group    16 (             CL) has    38 elements
Group    17 ( Water_and_ions) has 317468 elements
Group    18 (         r_1-50) has   604 elements
Select a group: Selected 18: 'r_1-50'
There are 50 residues in your selected group
dssp cmd='/home/vagrant/.local/bin/mkdssp -i ddedJBB2 2>/dev/null'
Reading frames from gro file '20hyp in water', 326182 atoms.
Reading frame       0 time    0.000   
Back Off! I just backed up ddedJBB2 to ./#ddedJBB2.1#


---------------------------------------------------------------------------------------------------------
When running by mkdssp alone, my command line is "dssp npt5.gro". The output is as follows:
Dropped unsupported records: (*followed a lot of numbers+letters*)

Error parsing PDB
Error trying to load file "npt5.gro"
Empty file?


----------------------------------------------------------------------------------------------------------------

Could you please tell me if this dssp package is supposed to work with gromacs? If not, how would I run dssp by itself? Many thanks in advance!

**Comment by drlemmus** [comment]
The .gro files are neither PDB nor mmCIF files. Could you test your dssp with a proper mmCIF and PDB file from the pdb. That way we can make sure the program itself works. After that we can dig a bit more.

**Comment by drlemmus** [comment]
Oh, and you need to test do_dssp with -ver 4. Because by default it assumes that you have an old version of dssp. See https://manual.gromacs.org/documentation/current/onlinehelp/gmx-do_dssp.html

**Comment by Chengeng-Yang** [comment]
> The .gro files are neither PDB nor mmCIF files. Could you test your dssp with a proper mmCIF and PDB file from the pdb. That way we can make sure the program itself works. After that we can dig a bit more.

I have tested .xtc files before and it didn't work -- does the xtc format work for this package?

**Comment by drlemmus** [comment]
These are not single structures. They are converted by do_dssp to pdb format.

**Comment by Chengeng-Yang** [comment]
> Oh, and you need to test do_dssp with -ver 4. Because by default it assumes that you have an old version of dssp. See https://manual.gromacs.org/documentation/current/onlinehelp/gmx-do_dssp.html

Here's the tested results. and it said not explicitly supported:
GROMACS:      gmx do_dssp, version 2020.1-Ubuntu-2020.1-1
Executable:   /usr/bin/gmx
Data prefix:  /usr
Command line:
  gmx do_dssp -s md5_1000ns.tpr -f 5traj3_w+m-p-c_-c_prot-frskip2.xtc -sc test-new-dssp.xvg -o test-new-dssp.xpm -n 1-50.ndx -ver 4

Reading file md5_1000ns.tpr, VERSION 2018 (single precision)
Reading file md5_1000ns.tpr, VERSION 2018 (single precision)
Not all residues were recognized (678 from 106546), the result may be inaccurate!
Group     0 (         System) has 326182 elements
Group     1 (        Protein) has  8714 elements
Group     2 (      Protein-H) has  4271 elements
Group     3 (        C-alpha) has   698 elements
Group     4 (       Backbone) has  2094 elements
Group     5 (      MainChain) has  2791 elements
Group     6 (   MainChain+Cb) has  3281 elements
Group     7 (    MainChain+H) has  3402 elements
Group     8 (      SideChain) has  5312 elements
Group     9 (    SideChain-H) has  1480 elements
Group    10 (    Prot-Masses) has  8714 elements
Group    11 (    non-Protein) has 317468 elements
Group    12 (          Water) has 317430 elements
Group    13 (            SOL) has 317430 elements
Group    14 (      non-Water) has  8752 elements
Group    15 (            Ion) has    38 elements
Group    16 (             CL) has    38 elements
Group    17 ( Water_and_ions) has 317468 elements
Group    18 (         r_1-50) has   604 elements
Select a group: Selected 18: 'r_1-50'
There are 50 residues in your selected group

WARNING: You use DSSP version 4, which is not explicitly
supported by do_dssp. Assuming version 2 syntax.

dssp cmd='/home/vagrant/.local/bin/mkdssp -i ddguK6PH 2>/dev/null'
Reading frame       0 time    0.000   
Back Off! I just backed up ddguK6PH to ./#ddguK6PH.1#

--------------------------------------------------------------------------------------------
And this version of dssp is the only dssp package I have in this virtual machine.. not sure why it is still assuming version 2 syntax.



--------------------------------------------------------------------------------
> These are not single structures. They are converted by do_dssp to pdb format.


I see, thanks for telling me that -- then xtc sounds okay to be used here.

**Comment by Chengeng-Yang** [comment]
Hi there,

A brief update -- I recompiled gromacs and now am able to use this package by itself (without gromacs) but it just seems like to have some certain preferences on the format of input pdb files, because it recognizes the pdb files from pdb database (please find the structure file, **1sem.pdb**, and the result file, **1sem.dssp**, in the attached zip file) but doesn't recognize my pdb file generated by gromacs. 

I also checked using this package with gromacs (gmx do_dssp -ver 4) but I don't think it recognized PPII structure in this case. -- Please find the results file **1sem.xvg**, in the attached zip file. Could you please tell me is it normal to have different results by running dssp by itself and running dssp with gromacs?


[1sem.zip](https://github.com/PDB-REDO/dssp/files/8229572/1sem.zip)

**Comment by drlemmus** [comment]
If PDB files from GROMACS do not work, please send us an example so we can figure out why. Note that DSSP expects properly formatted PDB files.

It is likely that GROMACS does not properly parse the DSSP output or is not aware that DSSP now finds PPII helices. This should be fixed on the side of GROMACS so I'm afraid I have to forward you to its developers for that.

**Comment by Chengeng-Yang** [comment]
> If PDB files from GROMACS do not work, please send us an example so we can figure out why. Note that DSSP expects properly formatted PDB files.

Attached please find a pdb file generated from gromacs but not recognized by dssp. Many thanks!
 [traj3-1000ns.zip](https://github.com/PDB-REDO/dssp/files/8233871/traj3-1000ns.zip)

> It is likely that GROMACS does not properly parse the DSSP output or is not aware that DSSP now finds PPII helices. This should be fixed on the side of GROMACS so I'm afraid I have to forward you to its developers for that.

No problem, I will try to contact gromacs developers for it. Thanks for your replies!

**Comment by drlemmus** [comment]
The PDB file is not valid. The most important thing missing is a HEADER record. Unnumbered REMARK records are also not cool.

**Comment by mhekkel** [comment]
DSSP only works with mmCIF or PDB files.

-maarten

Op 10-03-2022 om 20:39 schreef Chengeng-Yang:
