### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by onlyonewater** [PDB-REDO/dssp#38]
when I run command `cmake --build . --config Release`, an error has shown:
`/home/localuser/boost/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)':
zlib.cpp:(.text+0x138): undefined reference to `crc32'
/home/localuser/boost/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::reset(bool, bool)':
zlib.cpp:(.text+0x1b1): undefined reference to `deflateReset'
zlib.cpp:(.text+0x1c6): undefined reference to `inflateEnd'
zlib.cpp:(.text+0x1d9): undefined reference to `inflateReset'
zlib.cpp:(.text+0x1f1): undefined reference to `deflateEnd'
/home/localuser/boost/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)':
zlib.cpp:(.text+0x3f3): undefined reference to `inflateInit2_'
zlib.cpp:(.text+0x447): undefined reference to `deflateInit2_'
/home/localuser/boost/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::xdeflate(int)':
zlib.cpp:(.text+0x184): undefined reference to `deflate'
/home/localuser/boost/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::xinflate(int)':
zlib.cpp:(.text+0x194): undefined reference to `inflate'`

**Comment by onlyonewater** [comment]
hi, @mhekkel , do you know why? I have no idea to fix this error.

**Comment by mhekkel** [comment]
This should not have happened. Apparently you are building with static boost libraries. In the CMakeLists.txt file there is a note at line 121 that says:

`Note: use -DBoost_USE_STATIC_LIBS=ON to use boost static libraries`

I think you will have to rebuild and reinstall libcifpp as well using that flag, since the makefile of libcifpp uses it to include a dependency on libz in case this flag is set.

**Comment by onlyonewater** [comment]
ok, thanks, I will have a try.
