### ISSUE TITLE
Compatibility with Concoord

### ISSUE THREAD

**Issue by TomUnter** [PDB-REDO/dssp#39]
Hi, thanks for maintaining dssp!

I recently tried to use dssp with Concoord, but no version from 2. until 4. worked. Older versions of dssp have been shown to have worked, but those are not available anymore.
I just wanted to ask if you happened to know what could cause this.
Dssp 2.2.1 I found on Debian, at least told me it was a bad lexical cast. Every other version just told me "empty protein, or no valid complete residues".

Using any dssp as a standalone worked perfectly fine.

Many thanks
Tom Unterleiter

**Comment by drlemmus** [comment]
This has probably something to do with the coordinate files CONCOORD writes out. Could you send us an example coordinate file that causes the issue.

**Comment by TomUnter** [comment]
Here is the output of concoord until it crashes, and the files used and outputted are attached as a zip.
Normally dist.dat should have the calculated distance constraints needed for further calculations but it is empty.

Thank you very much

/data/tom/ssptest ]$ dist -p 1pgaohneM.pdb -dssp mkdssp 
Select a set of Van der Waals parameters:
1: OPLS-UA (united atoms) parameters
2: OPLS-AA (all atoms) parameters
3: PROLSQ repel parameters
4: Yamber2 parameters
5: Li et al. parameters
6: OPLS-X parameters (recommended for NMR structure determination)
1
Selected parameter set 1
copying /data/tom/CCPBSA/concoord_2.1.2/lib/ATOMS_oplsua.DAT to ATOMS.DAT in current working directory
copying /data/tom/CCPBSA/concoord_2.1.2/lib/MARGINS_oplsua.DAT to MARGINS.DAT in current working directory
Select a set of bond/angle parameters:
1: Concoord default parameters
2: Engh-Huber parameters
1
Selected parameter set 1
copying /data/tom/CCPBSA/concoord_2.1.2/lib/BONDS.DAT.noeh to BONDS.DAT in current working directory
-------------------------------------------------
dist.exe - build date: Thu Jan 24 11:26:08 CET 2013                                
Process started with PID:  2368420
on host: bccb12
in directory: /data/tom/ssptest
on: 27/06/0022 at: 10:15:27
-------------------------------------------------
command line options:
pdb input coordinate file...........: 1pgaohneM.pdb                           
dssp executable.....................: mkdssp                                  
non-bonded cut-off radius...........:   4.00 A + VDW sum
minimal nr. of distances per atom...:     50
output distances....................: dist.dat                                
output coordinates (PDB)............: dist.pdb                                
output coordinates (GROMOS87).......: dist.gro                                
hydrogen atoms (if any) will be removed
non-bonded contacts of starting structure will be preserved
processing input...
total number of atoms       :      428
number of residues          :       55
number of atoms to be used  :      428
starting DSSP calculation...
DSSP could not be created due to an error:
empty protein, or no valid complete residues
Something went wrong during the DSSP calculation!
[failed_concoord.zip](https://github.com/PDB-REDO/dssp/files/8990051/failed_concoord.zip)

**Comment by drlemmus** [comment]
The dist.pdb lacks a CRYST1 record which is sort of a minimum requirement for a valid PDB file. The best thing you can do is take this up with the CONCOORD developers. Feel free to CC me in.
