### ISSUE TITLE
PDB2Cif error

### ISSUE THREAD

**Issue by Yiqiu-Zhang** [PDB-REDO/dssp#43]
Hi 
I am using mkdssp for my own database. For some pdb files the server gives the massage below.
can you tell me what is causing it？ 
Thanks a lot.
mkdssp: /libcifpp/src/PDB2Cif.cpp:5512: PDBFileParser::ParseCoordinate(int)::<lambda(atomRec&, atomRec&)>: Assertion `d != 0' failed.

**Comment by mhekkel** [comment]
Most likely you are trying to read a PDB file containing atom numbers that are not unique.

May I suggest you start using mmCIF files instead of PDB files?
