### ISSUE TITLE
cmake compilation fails (libconfig not found)

### ISSUE THREAD

**Issue by vcojocaru** [PDB-REDO/dssp#45]
Hi ! 

I am trying to build the dssp excutable, so I built first libcifpp in a directory "/apps/dssp/4.0" (cmake -DCMAKE_INSTALL_PREFIX=/apps/dssp/4.0 -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11). This worked well but when I tried to build dssp (cmake -DCMAKE_INSTALL_PREFIX=/apps/dssp/4.0 -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11) I get the error below. I am on an openSUSE-Tumbleweed machine and I have libconfig installed. My default compiler is GCC 12 but I am trying to build with GCC 11 because libcifpp does not build with GCC 12.

Do you have any idea why is this happening and how to fix it ?

Thank you

Best wishes
Vlad

---ERROR----

CMake Error at CMakeLists.txt:127 (target_link_libraries):
  Target "mkdssp" links to:

    libconfig::libconfig

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by mhekkel** [comment]
Yes, my fault. I'm in the proces of redesigning the packaging and distribution of my code. And apparently, I broke it.

For now, things might work if you install https://github.com/mhekkel/libconfig.git and https://github.com/mhekkel/gxrio.git before building the other code.

**Comment by vcojocaru** [comment]
Thanks ! Indeed, with installing those codes separately I managed to build dssp

**Comment by learner-NKH** [comment]
Hi，

I'm trying to install dssp, when I run "cmake .." in the directory build, I got an error below:

########################################
CMake Error at CMakeLists.txt:110 (find_package):
  By not providing "Findlibconfig.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "libconfig", but CMake did not find one.

  Could not find a package configuration file provided by "libconfig" with
  any of the following names:

    libconfigConfig.cmake
    libconfig-config.cmake

  Add the installation prefix of "libconfig" to CMAKE_PREFIX_PATH or set
  "libconfig_DIR" to a directory containing one of the above files.  If
  "libconfig" provides a separate development package or SDK, be sure it has
  been installed.
#########################################

I have installed the two repo you mentioned above, and noticed  https://github.com/mhekkel/libconfig.git has the file "libconfigCondig.cmake", so it confused me, to why the error still appears.

**Comment by vcojocaru** [comment]
You need to set the CMAKE_PREFIX_PATH to the locations where you installed the codes
