### ISSUE TITLE
Exception: DSSP failed to produce an output

### ISSUE THREAD

**Issue by kanghui-learning** [PDB-REDO/dssp#47]
Hi!

I used a simple test script to check if dssp works well, as below:

class Test_Dssp():
    def __init__(self):
        self.parser = Bio.PDB.PDBParser()

    def test_dssp(self, inputfile, pdbname):
        structure = self.parser.get_structure(pdbname,inputfile)
        for model in structure:
            dssp = DSSP(model,inputfile, dssp='/MAPATH/mambaforge/envs/Geopacker01/bin/dssp')
            print(type(dssp))

if __name__ == "__main__":
    inputfile = '/MYPATH/example/3MPC_A.pdb'
    pdbname = '3MPC'
    if 1:
        Test = Test_Dssp()
        Test.test_dssp(inputfile, pdbname)
    else:
        dssp_tuple = dssp_dict_from_pdb_file(inputfile)
        dssp_dict = dssp_tuple[0]
        print(dssp_dict['A',(' ', 1, ' ')])

And the error occured:

UserWarning: /MYPATHi/mambaforge/envs/Geopacker01/bin/mkdssp: symbol lookup error: /MYPATH/mambaforge/envs/Geopacker01/bin/mkdssp: undefined symbol: _ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

  warnings.warn(err)
Traceback (most recent call last):
  File "my_scripts/test_dssp.py", line 26, in <module>
    Test.test_dssp(inputfile, pdbname)
  File "my_scripts/test_dssp.py", line 18, in test_dssp
    dssp = DSSP(model,inputfile, dssp='/MYPATH/mambaforge/envs/Geopacker01/bin/mkdssp')
  File "MYPATH/mambaforge/envs/Geopacker01/lib/python3.6/site-packages/Bio/PDB/DSSP.py", line 438, in __init__
    dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
  File "/MYPATH/mambaforge/envs/Geopacker01/lib/python3.6/site-packages/Bio/PDB/DSSP.py", line 254, in dssp_dict_from_pdb_file
    raise Exception("DSSP failed to produce an output")
Exception: DSSP failed to produce an output

It's almost the simplest case, I don't know why this error.

The dssp is installed by "conda install -c salilab dssp", while the version is 3.0.0

The version of biopython is 1.79.

**Comment by mhekkel** [comment]
I'm afraid this is an error in the way Conda creates or repackages dssp software. This should not happen with code you can download from github. Besides, the newest dssp code here doesn't use boost program options anymore.

**Comment by kanghui-learning** [comment]
> 

Tks, I will try to build this by the source code.

**Comment by kanghui-learning** [comment]
Hi,

I installed dssp by building the source code as you said. However, when I run the same test, that error still appeared.

  /root/mambaforge/lib/python3.9/site-packages/Bio/PDB/DSSP.py:252: UserWarning: parse error at line 1: This file does not seem to be an mmCIF file
  
    warnings.warn(err)
  Traceback (most recent call last):
    File "/MYPATH/GeoPacker/my_scripts/test_dssp.py", line 26, in <module>
      Test.test_dssp(inputfile, pdbname)
    File "/MYPATH/GeoPacker/my_scripts/test_dssp.py", line 18, in test_dssp
      dssp = DSSP(model,inputfile)
    File "/root/mambaforge/lib/python3.9/site-packages/Bio/PDB/DSSP.py", line 438, in __init__
      dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
    File "/root/mambaforge/lib/python3.9/site-packages/Bio/PDB/DSSP.py", line 254, in dssp_dict_from_pdb_file
      raise Exception("DSSP failed to produce an output")
  Exception: DSSP failed to produce an output

The mkdssp version is 4.1.0
The biopython version is 1.79

**Comment by drlemmus** [comment]
Could you send the input file? You seem to be using a pdb file as input. This should work but there are some requirement in term of the file format.

**Comment by kanghui-learning** [comment]
Hi, you can download the input file through this link 

https://drive.google.com/file/d/1B6u48k1EIbLuddxRqiVPF_8iSEH0xICI/view?usp=share_link

**Comment by mhekkel** [comment]
Thanks for sending that file, which is not a PDB file:

Every PDB file should start with a header line. There are other fields that are mandatory, but the HEADER line is a must to detect if a file contains PDB data.

See https://www.wwpdb.org/documentation/file-format-content/format33/v3.3.html

And specifically:

https://www.wwpdb.org/documentation/file-format-content/format33/sect1.html  Section Order of Records.

Software based on libcifpp transparently works with PDB and mmCIF files, even ones compressed with gzip. But that means you have to play nice and at least provide that HEADER line. Just a bunch of ATOM records is not a PDB file.

**Comment by kanghui-learning** [comment]
Thanks for this information. I've understood what an actual PDB file should be.

However, there were still some problems when I tested using a PDB file(6T1Z.pdb) downloaded from the PDB database...

The output of `dssp_dict_from_pdb_file(inputfile)` is just empty, I try three different pdb files(6oo8.pdb, 6t1z.pdb, 3ev4.pdb), and the results are all empty. 

Those pdb files can be downloaded at https://drive.google.com/drive/folders/14Uj5aBHnX3bIXMsTCccvH-wmkO9joEZD?usp=share_link

**Comment by mhekkel** [comment]
You are using some kind of wrapper around dssp. That wrapper is not working properly. I've tried your PDB files and they produce perfectly fine output.

Try this in a terminal:

`mkdssp 6tiz.pdb`

and you will see that it outputs the new format, your input converted into mmCIF format annotated with the secondary structure information. If you prefer the old DSSP format, you run:

`mkdssp 6tiz.pdb --output-format dssp`

which will write the output to the terminal, alternatively you can do:

`mkdssp 6tiz.pdb 6tiz.dssp`

And that will produce a file called 6tiz.dssp containing the results in the old DSSP format.

I'm afraid you will have to ask the developers of the wrapper script to update their code to work with the current version of mkdssp.

**Comment by kanghui-learning** [comment]
Thanks! That worked, so mkdssp was installed correctly. Maybe the wrapper will work well with an early version of mkdssp, I will have a try.
