### ISSUE TITLE
PDB input: parse error at line 1: This file does not seem to be an mmCIF file

### ISSUE THREAD

**Issue by yunxiangz** [PDB-REDO/dssp#48]
Thanks for the outstanding work, I am new to the dssp!

I used the following command to process a PDB file:
/usr/local/bin/mkdssp ./xxx.pdb ./xxx.dssp
 
However, I got the following error:
parse error at line 1: This file does not seem to be an mmCIF file

Could you please help with the correct command for PDB inputs please?

**Comment by drlemmus** [comment]
Could you send us the input file so we can test

**Comment by yunxiangz** [comment]
Hi drlemmus,

Thanks for your prompt reply! The file I tried is attached below:

[6ymw_B.pdb.zip](https://github.com/PDB-REDO/dssp/files/10023008/6ymw_B.pdb.zip)

**Comment by drlemmus** [comment]
DSSP requires a valid mmCIF or PDB file as input. Your file is neither; it is a bunch of ATOM records. If you use a PDB file with at least a HEADER record and a CRYST1 record (the bare minimum, really), DSSP will see it as PDB file and should run properly. Without it, it assumes the default mmCIF format.
