### ISSUE TITLE
cmake error @ cbaakman 

### ISSUE THREAD

**Issue by K-kiran90** [PDB-REDO/dssp#52]
-- Not using resources since mrc was not found
CMake Error at CMakeLists.txt:106 (find_package):
  By not providing "Findlibmcfp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libmcfp", but
  CMake did not find one.

  Could not find a package configuration file provided by "libmcfp" with any
  of the following names:

    libmcfpConfig.cmake
    libmcfp-config.cmake

  Add the installation prefix of "libmcfp" to CMAKE_PREFIX_PATH or set
  "libmcfp_DIR" to a directory containing one of the above files.  If
  "libmcfp" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/kiran/Downloads/dssp-trunk (1)/dssp-trunk/build/CMakeFiles/CMakeOutput.log".
See also "/home/kiran/Downloads/dssp-trunk (1)/dssp-trunk/build/CMakeFiles/CMakeError.log".

**Comment by mhekkel** [comment]
Thanks for pointing out I needed to update the README.

**Comment by K-kiran90** [comment]
how to fix it

This error when i installing DSSP4 version

  Could not find a package configuration file provided by "libmcfp" with any
  of the following names:

    libmcfpConfig.cmake
    libmcfp-config.cmake

  Add the installation prefix of "libmcfp" to CMAKE_PREFIX_PATH or set
  "libmcfp_DIR" to a directory containing one of the above files.  If
  "libmcfp" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/kiran/Downloads/dssp-trunk _1/dssp-trunk/build/CMakeFiles/CMakeOutput.log".
See also "/home/kiran/Downloads/dssp-trunk _1/dssp-trunk/build/CMakeFiles/CMakeError.log".
