### ISSUE TITLE
Allow DSSP to work with alternative header

### ISSUE THREAD

**Issue by DaniBodor** [PDB-REDO/dssp#54]
Hi, I found this comment below in a previous issue:

> DSSP requires a valid mmCIF or PDB file as input. Your file is neither; it is a bunch of ATOM records. If you use a PDB file with at least a HEADER record and a CRYST1 record (the bare minimum, really), DSSP will see it as PDB file and should run properly. Without it, it assumes the default mmCIF format.

> _Originally posted by @drlemmus in https://github.com/PDB-REDO/dssp/issues/48#issuecomment-1317313626_
            

Is there any particular reason why a file without header is not allowed to be read?

I have a project where we have a large number of pdb files that do not include a formal header (instead of "HEADER" they start with "EXPDATA" in the first line. It would of course be possible to run a few lines to adjust each file to include a header before running dssp, but it would actually be nice if this weren't necessary.
Alternatively, is there a way to make DSSP recognize "EXPDATA" as an alternative to "HEADER"?

**Comment by drlemmus** [comment]
DSSP uses the HEADER record to distinguish PDB from mmCIF. Obviously we could code around that but as HEADER is a required record for PDB format, we are not inclined to do so. Please have a look here: https://www.wwpdb.org/documentation/file-format-content/format33/sect1.html#Order
You'll see that we are actually still reasonably forgiving when it comes to PDB format.

**Comment by DaniBodor** [comment]
Can you tell me exactly which elements are required in the pdb for DSSP to run?

I have tried writing a HEADER line to the top of the file, plus 'COMPND XXX', 'SOURCE XXX', and 'AUTHOR XXX' lines (in that order) underneath. This now works locally on my own system (which uses 4.2.2.1), but not in the GitHub CI for [our repo](https://github.com/DeepRank/deeprank-core/pull/387) (which uses by default 4.0.4-1 and I can't figure out how to force install the version I have locally).

I realize that Ideally I should actually use properly formatted PDB files to start with, but unfortunately, we have a large number of files created by PANDORA software, which formats pdb files as just lists of ATOM entries and are bound to those files for the moment.

**Comment by mhekkel** [comment]
For that version of DSSP you still needed the CRYST1 record. You can put any value in there, dssp does not require sensible data here.

**Comment by DaniBodor** [comment]
that solved it!

**Comment by drlemmus** [comment]
@DaniBodor Thank you for asking an update in PANDORA. That's the way to go!
