### ISSUE TITLE
Error parsing PDB with GROMACS generated PDB files

### ISSUE THREAD

**Issue by Theguywhooccurs** [PDB-REDO/dssp#55]
Hello,
I have GROMACS generated PDB files with are from MD simulations I am running on IDPs. DSSP (4.0) gives the following error.
"When validating _pdbx_poly_seq_scheme.pdb_strand_id: Value ' ' does not match type expression for type code"
This happens specifically on line 2 which is the CRYST1 properties.

Any help would be appreciated.

**Comment by drlemmus** [comment]
The error message refers to your coordinates. Is the chainID specified? This is mandatory in PDB format but that are programs that do not write it.
