### ISSUE TITLE
apt-get

### ISSUE THREAD

**Issue by cbaakman** [PDB-REDO/dssp#58]
When installing dssp with apt get, the highest version encountered is `dssp/focal 3.0.0-3build1 amd64`.

What can we do to make sure this becomes a 4.0 version?

**Comment by mhekkel** [comment]
Simple, upgrade your OS.

Ubuntu 22.04 LTS comes with version 4.0.4. Ubuntu Lunar Lobster comes 
with 4.2.2.

Debian has 4.2 in testing and 4.0 in stable.



Op 25-05-2023 om 17:35 schreef cbaakman:

**Comment by cbaakman** [comment]
Thanks!
