### ISSUE TITLE
Cifpp error

### ISSUE THREAD

**Issue by farmacyst99** [PDB-REDO/dssp#59]
Hey, 
I'm trying to install dssp on my ubuntu WSL 2, while installing it is showing following error: 

CMake Error at CMakeLists.txt:108 (find_package):
  By not providing "Findcifpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "cifpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "cifpp" (requested
  version 5.0.8) with any of the following names:

    cifppConfig.cmake
    cifpp-config.cmake

  Add the installation prefix of "cifpp" to CMAKE_PREFIX_PATH or set
  "cifpp_DIR" to a directory containing one of the above files.  If "cifpp"
  provides a separate development package or SDK, be sure it has been
  installed. 
![image](https://github.com/PDB-REDO/dssp/assets/128505622/661a91be-4c3d-4dda-89d5-822866843d40)

Can you please help me with this I have installed all the other libraries requested in the READme

**Comment by mhekkel** [comment]
The cifpp package was updated yesterday to version 5.0.8. Did you install that version? And where did you install it, in the default location (/usr/local) or somewhere else? In the latter case you may need to specify that path in the CMAKE_PREFIX_PATH as stated by the error message.

So, e.g., if you installed libcifpp in /opt you would then need to run the cmake command for dssp like this:

```bash
git clone https://github.com/PDB-REDO/dssp.git
cd dssp
mkdir build
cmake -S . -B build -DCMAKE_PREFIX_PATH=/opt
cmake --build build
```

**Comment by drlemmus** [comment]
Stale
