### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by n-frazee** [PDB-REDO/dssp#6]
Hey DSSPers!

I'm running into an issue during install that it cannot find something in the ./doc dir. This checks out as the ./doc dir does not exist. Guessing this is ultimately a problem with something in the `$ make`?

Any help is appreciated!

Nick

$ ./configure
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++17 features with -std=c++17... yes
checking whether C++ compiler accepts -fstandalone-debug... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... 
x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a sed that does not truncate output... /bin/sed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for mrc... no
configure: WARNING: The mrc application was not found, not using resources.
checking how to run the C++ preprocessor... g++ -std=c++17 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking filesystem usability... yes
checking filesystem presence... yes
checking for filesystem... yes
checking for boostlib >= 1.65.1 (106501)... yes
checking whether the Boost::IOStreams library is available... yes
checking for exit in -lboost_iostreams... yes
checking whether the Boost::Program_Options library is available... yes
checking for exit in -lboost_program_options... yes
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
checking for CIFPP... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for main in -lz... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for main in -lbz2... yes
configure: creating ./config.status
config.status: creating GNUmakefile
config.status: creating src/config.hpp

$ make
mkdir -p obj
rm -f version-info-*.txt
>> src/mkdssp.cpp
-> mkdssp
nfrazee@cable:~

$ sudo make install
install -d /usr/local/bin
install mkdssp /usr/local/bin/mkdssp
install -d /usr/local/share/man/man1
install -m 644 doc/mkdssp.1 /usr/local/share/man/man1/mkdssp.1;
install: cannot stat 'doc/mkdssp.1': No such file or directory
make: *** [GNUmakefile:164: install] Error 1

**Comment by mhekkel** [comment]
Thanks Nicolas for reporting this issue. This should be fixed now (by moving the man page to the location the makefile was looking for it).
