### ISSUE TITLE
Downcase residua unknown

### ISSUE THREAD

**Issue by jackhu3301** [PDB-REDO/dssp#60]
![image](https://github.com/PDB-REDO/dssp/assets/24487383/75e17eac-156f-4a7b-8d06-2c621b1aff34)
What does the 'a' mean? It is 'C' of 122 possition in  PDB-1ETR .  Would you mind share some reference about this ? Thank you very much.
![BE6766B0-F9CF-4c16-B42C-00DE2990C1B6](https://github.com/PDB-REDO/dssp/assets/24487383/9454ddda-c391-4781-92e5-0970f6673fb3)

Here is 1etr.pdb and 1etr.dssp:
[1etr.txt](https://github.com/PDB-REDO/dssp/files/12024381/1etr.txt)
[1etr_dssp.txt](https://github.com/PDB-REDO/dssp/files/12024391/1etr_dssp.txt)

**Comment by drlemmus** [comment]
It is a way of mapping connectivity of disulfide bridges. Described in the original DSSP paper and in the current documentation at https://pdb-redo.eu/dssp/about (see the AA section).
