### ISSUE TITLE
Request for release binary

### ISSUE THREAD

**Issue by rcedgar** [PDB-REDO/dssp#61]
Any chance you could post a Linux binary? It would save me some time, I'm finding building from source is not so easy, there are nested dependencies for the libraries. Thanks for your consideration!

**Comment by drlemmus** [comment]
Have a look here: https://pdb-redo.eu/dssp/download

**Comment by rcedgar** [comment]
Yes, I saw that, but the link to the binary (https://pdb-redo.eu/dssp/others/mkdssp.gz) gives a Not Found error.

**Comment by drlemmus** [comment]
Ah, you should have said that in the first place then. Sorry for the inconvenience. We'll get back to you once it is fixed.

**Comment by rcedgar** [comment]
Yes sorry, I actually I had forgotten -- FYI I spent maybe an hour or two trying several different ways to get DSSP files for some PDB records and none of them worked for me easily. FWIW I also could not figure out the rsync or ftp downloads, the downloads just hung. Suggestion -- ut would be easier for users if the binary was posted as with releases on github, or that link to the binary is included in the repo README.md.

**Comment by drlemmus** [comment]
Could you be a bit more specific. Which PDB entries? Did you use the databank?
The rsync is a literal copy paste on you command line. What went wrong there? Did you use the one on pdb-redo.eu? We don't provide FTP.

**Comment by rcedgar** [comment]
sorry, didn't keep detailed notes. a binary is what I really need because I have many new AlphaFold structure predictions.

**Comment by mhekkel** [comment]
Both a linux as well as a Window executable are now available at:

https://github.com/PDB-REDO/dssp/releases/latest
