### ISSUE TITLE
dssp-4.4.0 introduces an automagic dependency on pandoc

### ISSUE THREAD

**Issue by pacho2** [PDB-REDO/dssp#64]
You can find information about automagic dependencies in:
https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies

The dep was added in https://github.com/PDB-REDO/dssp/commit/3056425604a48a62e6ac824bcf9b77a2c4d79ca5

For us (Gentoo downstream) it is a bit problematic as the build will behave differently depending on users having pandoc installed or not. One way to workaround the bug would be to always require pandoc, but that would add an unconditional dependency that most users won't really need as, per the comments in CMake files, it is only needed to re-generate the documentation

Thanks a lot

**Comment by mhekkel** [comment]
I'll change this to hide behind an option that is OFF by default (GENERATE_DOCUMENTATION).

But this raises a question: the same goes for having mrc installed or not. If you have mrc, the executable will be built with resources, if mrc is not available you will have to have the dictionary files installed somewhere. Is that an automagic dependency as well?

**Comment by pacho2** [comment]
Yeah, that would also be automagic as running with the same options at configure stage will lead to different results and dependencies following the packages that are present at build time

**Comment by mhekkel** [comment]
After all, this is not really a problem IMHO. At the install stage, the dictionaries are always installed regardless whether mrc was available or not. The only difference is that the executable built with mrc can be copied to a machine without these files and will still work.

Anyway, there is now a version 4.4.1 where documentation generation is optional. I'll leave it like this but feel free to suggest changes to change the way resources are used if you think that is needed.

**Comment by pacho2** [comment]
Thanks a lot!

**Comment by pacho2** [comment]
The switch works fine... on the other hand, I still need to manually install the generated mkdssp.pdf file, is that intended or some install rule is missing?

**Comment by mhekkel** [comment]
The .pdf contains the same text as the man page. Besides, I don't know where you would like to have the pdf placed anyway. So you could say it is intended.

**Comment by pacho2** [comment]
Ah, I thought it was meant to be placed under /usr/share/doc with the README file. But being the same as the man page, we probably can stay simply disabling its generation and relying on the man page

Thanks for the info and help!
