### ISSUE TITLE
DSSP's webserver is misbehaving

### ISSUE THREAD

**Issue by alexmplastow** [PDB-REDO/dssp#67]
I was advised to post here by Coos Baakman,

I uploaded a copy of 1R9K from my personal machine onto https://www3.cmbi.umcn.nl/xssp/, which crashed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/xssp_api/factory.py", line 150, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/xssp_api/tasks.py", line 66, in mkdssp_from_pdb
    output, error = _execute_subprocess(args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/xssp_api/tasks.py", line 47, in _execute_subprocess
    raise RuntimeError(f"{args} error:\n{p.stderr}")
RuntimeError: ['mkdssp', '--output-format', 'dssp', '/tmp/xssp-api/uploads/chimera_10.pdb'] error:
mkdssp: /deps/libcifpp/src/row.cpp:79: cif::row_initializer::row_initializer(cif::row_handle): Assertion `rh.m_row' failed.

But if I upload the file using the PDB Id, and enter 1R9K in the textbox below, the issue resolves normally. I so happen to be studying some proteins which were generated via alphafold, so I can't look up most of them using the PDB Id. The same issue crops up if I use one such protein. 

This seems to be a simple use case, so I suppose something is going wrong on the server side.

The issue can be reproduced if you upload the file downloaded from https://www.rcsb.org/structure/1r9k and upload it at https://www3.cmbi.umcn.nl/xssp/

**Comment by mhekkel** [comment]
Please use https://pdb-redo.eu/dssp instead of the one at the UMCN. The latter is a bit out of date and should perhaps be phased out.
