### ISSUE TITLE
DSSP visualization tool

### ISSUE THREAD

**Issue by natarajmtech** [PDB-REDO/dssp#7]
Any visualization tool of DSSP output file available. Can developer recommend any visualization software for DSSP ?

**Comment by drlemmus** [comment]
Depends a bit on what you want, but the options are limited. The new version of DSSP annotates coordinate files in PDB and mmCIF format and there are molecular graphics programs that use this information. I think PyMOL does this by default for PDB files, but that only shows you helices and strands. The annotation of mmCIF files is much richer (the other secondary structure elements are also listed), but I don't know a program that used these for visualisation.  
If you want to show/use the DSSP one-letter codes in 1D from a DSSP file, theuis might give you some help: https://ssbio.readthedocs.io/en/latest/instructions/dssp.html

**Comment by natarajmtech** [comment]
Thank you Drlemmus for your reply. I will explore the options that you have suggested.
