### ISSUE TITLE
Feature request: Conda package support for DSSP

### ISSUE THREAD

**Issue by gcroci2** [PDB-REDO/dssp#72]
We currently use DSSP 4.4.0 in [DeepRank2](https://github.com/DeepRank/deeprank2) for secondary structure feature generation. However, we've encountered many installation issues, such as apt-get and sudo privileges not always available, error-prone manual installations from source, and version discrepancies based on Ubuntu versions.

After encountering challenges during the installation process, we are exploring alternative solutions, with the most promising option being [the release of DSSP on Conda](https://conda-forge.org/#add_recipe). The addition of Conda package support for DSSP would significantly simplify the installation process, ensuring a smoother experience for users, and benefiting not only our project but also the broader community that relies on DSSP. Without this improvement, we're considering removing DSSP from our package.

**Comment by drlemmus** [comment]
Making conda packages really isn't within our remit. What we can do is help you with the build process or with our distributed binaries (https://github.com/PDB-REDO/dssp/releases/tag/v4.4.0). 
I see your are looking into containers. For HPC solutions Docker is considered unsafe but Singularity is safe and commonly accepted. We are perfectly fine with you distributing DSSP in the context of a DeepRank2 container.

**Comment by drlemmus** [comment]
Would this be of any help to you: https://github.com/PDB-REDO/dssp/pull/62

**Comment by gcroci2** [comment]
Thanks for the fast reply @drlemmus!

We already managed to create a container for DeepRank2, including DSSP installation from the binaries, but the container is only for trying out our package, and Docker is not suited for our real use case applications. So we're now thinking about releasing everything on conda. 

Would it work for you if we set DSSP ourselves on conda?

**Comment by drlemmus** [comment]
Yes, feel free to do so

**Comment by LourensVeen** [comment]
It looks like Inria has packaged dssp and cifpp for Conda: https://anaconda.org/sbl/dssp
