### ISSUE TITLE
libmcfp changes break installation

### ISSUE THREAD

**Issue by merterden98** [PDB-REDO/dssp#76]
As [commit](https://github.com/mhekkel/libmcfp/commit/5ddeaf0180e1497eb9cc37ea7acbb84b9ea9a1e4) introduced changes to the makefile and the package name, building dssp from source fails.

**Comment by mhekkel** [comment]
Yes, that was a rather stupid action from my side... I'm working on it

**Comment by mhekkel** [comment]
Should be fixed now
