### ISSUE TITLE
feature request: input/ouput without writting files to disk

### ISSUE THREAD

**Issue by lmiq** [PDB-REDO/dssp#81]
Dear authors,

We have been using DSSP to analyze molecular dynamics simulations. We have wrapped it into [a package](https://m3g.github.io/ProteinSecondaryStructures.jl) that performs this analysis by writing each frame of a trajectory to a PDB file and then using DSSP  to read it and compute the output, which has to be read then again. 

Is there any chance to provide an interface in which these input/output data does not need to be written to the disk? For example by providing a command line parameter such as `-input_file """CRYST  \n ATOM ..."""` or something of the sort? 

PS: If the input/output was less PDB/mmCIF format centric (meaning, if the data passed was just the lower-level data that is required for the computations) that would be even better.

Thank you.

**Comment by mhekkel** [comment]
Dear Leandro,

Of course it is possible to change mkdssp to read from stdin when no file is specified. But there are alternatives. First of all, mkdssp (the program) is a light wrapper around libdssp. You could try to create a Julia plugin (if at all possible) that provides access to DSSP directly. A bit of work but might be worth the effort.

Another option is to use named pipes. You can create a fifo using system calls (use `man 3 mkfifo` for documentation) and pass that to mkdssp. That will create a temp file, but will not write to disk. You still have to remove the fifo after running mkdssp.

The last option is available right now and will be similar in performance to using a `popen` like setup, the option you are asking for.

**Comment by lmiq** [comment]
Thanks for the tips! I'll try that out!
