### ISSUE TITLE
Dictionary not found or defined (mmcif_pdbx)

### ISSUE THREAD

**Issue by drewaight** [PDB-REDO/dssp#83]
Hello all I feel like this is a simple question. I am trying to install dssp on my HPC where I have no sudo permissions, I can compile the software with cmake (conda version) and I install with cmake --install build --prefix /home/myname/tools/dssp/bin (add this directory to my path) 

When I try to run I get the error 

"Dictionary not found or defined (mmcif_pdbx)"

Obviously the install is not configured to look in the right place for the mmcif_pdbx_v50.dic (I have tried placing it in "/dssp/share/libcifpp/" and rerunning cmake build and install. 

I have also read the Makefile to the best of my ability and looked for how to configure an alternate path for the Dictionary but am unable to find how to configure this variable during the cmake build and install process.

Any help would be greatly appreciated. Thanks..

Drew

**Comment by mhekkel** [comment]
DSSP uses libcifpp and libcifpp uses a mechanism to locate resource data as specified here: [https://www.hekkelman.net/libcifpp-doc/resources.html](https://www.hekkelman.net/libcifpp-doc/resources.html)

The resource directory can be specified at compile time using the CIFPP_DATA_DIR variable. You can use a gui interface for cmake (e.g. _ccmake_) to specify this variable, or configure with:

```console
cmake -S . -B build -DCIFPP_DATA_DIR=$HOME/somepath
```

Tip: you can also use the more standard way of installing your local software in $HOME/.local If you do so, you should have $HOME/.local/bin in your PATH variable and then you can configure cmake like this:

```console
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$HOME/.local
```

**Comment by drewaight** [comment]
Thanks so much... it works!
