### ISSUE TITLE
Publish as Conda package

### ISSUE THREAD

**Issue by padix-key** [PDB-REDO/dssp#86]
Hi, I created a WIP Conda recipe for DSSP in the `conda-forge` channel to make this new DSSP version also available for Conda users: https://github.com/conda-forge/staged-recipes/pull/27330

I would like to add @mhekkel as maintainer for the Conda package as well, if you agree.

**Comment by mhekkel** [comment]
Thanks very much for your efforts, and yes, of course you can add me as maintainer.

**Comment by padix-key** [comment]
> Thanks very much for your efforts, and yes, of course you can add me as maintainer.

Thanks. @mhekkel could you leave a comment in https://github.com/conda-forge/staged-recipes/pull/27330 confirming I can add you? The CI requires it

**Comment by padix-key** [comment]
As I haven't heard back for a while I will only add me for now. Feel free to reach out to me in this PR or in the generated `conda-forge` feedstock (should be https://github.com/conda-forge/dssp as soon as the recipe is merged) in the future, when I should add you as well.
