### ISSUE TITLE
Missing components.cif

### ISSUE THREAD

**Issue by lx19930** [PDB-REDO/dssp#89]
Hi,
I just installed the package from source and ran it with biopython. A error showed up:

/home/xing.liu/miniconda3/envs/msa_attention/lib/python3.12/site-packages/Bio/PDB/DSSP.py:199: UserWarning:
Configuration error:

The attempt to retrieve compound information for "NAG" failed.

This information is searched for in a CCD file called components.cif or
components.cif.gz which should be located in one of the following directories:

"/work/SimBioSys/Xing/dssp/share/libcifpp"
"/work/SimBioSys/Xing/dssp/share/libcifpp"
"/work/SimBioSys/Xing/dssp/share/libcifpp"

(Note that you can add a directory to the search paths by setting the
LIBCIFPP_DATA_DIR environmental variable)

On Linux an optional cron script might have been installed that automatically updates
components.cif and mmCIF dictionary files. This script only works when the file
libcifpp.conf contains an uncommented line with the text:

update=true

If you do not have a working cron script, you can manually update the files
in /var/cache/libcifpp using the following commands:

curl -o /work/SimBioSys/Xing/dssp/var/cache/libcifpp/components.cif https://files.wwpdb.org/pub/pdb/data/monomers/components.cif
curl -o /work/SimBioSys/Xing/dssp/var/cache/libcifpp/mmcif_pdbx.dic https://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic
curl -o /work/SimBioSys/Xing/dssp/var/cache/libcifpp/mmcif_ma.dic https://github.com/ihmwg/ModelCIF/raw/master/dist/mmcif_ma.dic

I am running it on a discovery server so I am not sure whether it is my problem.
And help would be appreciated.
Xing

**Comment by mhekkel** [comment]
This is an issue in conda that needs to be fixed. We're working on that.

For now, please read that error message completely. I believe that everything you need to know to fix this issue is in the error message text.
