### ISSUE TITLE
DSSP issue with building

### ISSUE THREAD

**Issue by izu0421** [PDB-REDO/dssp#9]
Hi, Thanks for your work. I am trying to install dssp and ran into a problem.

The configuration is file `./configure --with-cif++=/home/yy/libcifpp`

However, when I build with `make` I get the following error:
`/usr/local/bin/mrc -o obj/mkdssp_rsrc.o /home/yy/libcifpp/rsrc/mmcif_pdbx_v50.dic`
`/usr/local/bin/mrc: error while loading shared libraries: ` `libboost_program_options.so.1.66.0: cannot open shared object file: No such file or directory`
`make: *** [GNUmakefile:139: obj/mkdssp_rsrc.o] Error 127`

Would you be able to help?
Thanks!

**Comment by mhekkel** [comment]
This is a generic Linux related question and not something specific to DSSP. But yes, I can help you.

You have two options. The first and preferred one is to rebuild your boost libraries as static libraries. For this, you should first clean the boost directory (using ./b2 clean) and then rebuild the libraries using `./b2 link=static` That way you get static libraries. If you now rebuild DSSP it will no longer need the shared libraries from boost.

The second option is to install boost (by running ./b2 install --prefix=/for/example/usr/local) and then add this path to the list of directories Linux looks for shared libraries. This is done by creating a file containing just this path in /etc/ld.config.so.d/ and then run ldconfig. As root.

I think the first option is easier :-)
