### ISSUE TITLE
Error while loading dictionary mmcif_pdbx.dic, while in conda-forge environment

### ISSUE THREAD

**Issue by vagkaratzas** [PDB-REDO/dssp#90]
Hi! I am trying to create an nf-core module from dssp to make it more useable by the bioinformatics Nextflow/nf-core community.
I am using the conda-forge::dssp=4.4.8 environment, and when I try to execute:
```
mkdssp 1tim.pdb test.dssp 
```
I get the following error:
```
Error while loading dictionary mmcif_pdbx.dic                                                                                                                                                                                                  │
│      >> basic_filebuf::underflow error reading the file: Is a directory 
```
Is there a solution for this?
Thanks!

**Comment by mhekkel** [comment]
This is not an issue with dssp itself, it is a configuration error in the conda environment. Please submit this bug to [the dssp feedstock in conda](https://github.com/conda-forge/dssp-feedstock/)
